- name: Nexxera DevOps Test
  hosts: target_instance
  become: true
  vars:
    app_name: java_app
    ftp_url: https://github.com/flametuner/nexxera_devops/raw/master/hello_world_java/ #ftp://user:password@localhost/
    file_name: helloworld.jar
    docker_users:
      - gustavo
  tasks:
    - name: Package | Install python-docker
      package:
        name: python-docker
        state: present
    # - name: Python | Install docker
    # - pip:
    #     name: docker
    - name: Directory | Create a directory if it does not exist
      file:
        path: "/temp/{{ app_name }}"
        state: directory
    - name: "Download | {{ file_name }}"
      get_url:
        url: "{{ ftp_url }}{{ file_name }}"
        dest: "/temp/{{ app_name }}/{{ file_name }}"
        force: true # Downloads everytime it changes
    - name: "Copy | Dockerfile"
      copy:
        src: ./Dockerfile
        dest: "/temp/{{ app_name }}/Dockerfile"
    - name: Image | Build Docker image
      docker_image:
        name: "{{ app_name }}:latest"
        force_source: true
        build:
          pull: true
          path: "/temp/{{ app_name }}/"
          args:
            FILE_NAME: "{{ file_name }}"
        source: build
    - name: Docker | Install container
      docker_container:
        name: "{{ app_name }}"
        image: "{{ app_name }}:latest"
        recreate: true
    - name: Docker | Prune everything
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
  roles:
    - role: geerlingguy.docker # Installs Docker
      become: true
